services:

  db:
    image: 'postgres:14-alpine'
    container_name: postgresql
    restart: always
    environment:
      - POSTGRES_DB=solobajos
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin1234
    ports:
      - "5433:5432"


  client:
    container_name: pgadmin
    image: 'dpage/pgadmin4'
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    depends_on:
      - db
    ports:
      - 5050:80